import { Link } from "wouter";
import { ArrowLeft, Download } from "lucide-react";
import { Button } from "@/components/ui/button";

export default function SafeAgreementTemplate() {
  const handleDownload = () => {
    // Create a downloadable SAFE agreement template
    const content = `
SIMPLE AGREEMENT FOR FUTURE EQUITY

Company: [COMPANY NAME]
Investor: [INVESTOR NAME]
Date: [DATE]

This certifies that in exchange for the payment by the Investor of $[AMOUNT] (the "Purchase Amount") on or about [DATE], [COMPANY NAME], a [STATE] corporation (the "Company"), hereby issues to the Investor the right to certain shares of the Company's Capital Stock, subject to the terms set forth below.

The "Valuation Cap" is $[VALUATION_CAP].
The "Discount Rate" is [DISCOUNT_RATE]%.

This instrument was prepared using the Y Combinator Safe template and adapted for use on the Fundry platform.

For the complete legal document, please consult with a qualified attorney.

Generated by Fundry - fundry.com
    `;
    
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'SAFE-Agreement-Template.txt';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="min-h-screen bg-gray-50">
      <header className="bg-white shadow-sm border-b">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex items-center justify-between h-16">
            <Link href="/" className="flex items-center text-navy-600 hover:text-navy-800">
              <ArrowLeft className="w-5 h-5 mr-2" />
              Back to Fundry
            </Link>
            <div className="flex items-center gap-4">
              <h1 className="text-xl font-semibold text-gray-900">SAFE Agreement Template</h1>
              <Button onClick={handleDownload} className="flex items-center gap-2">
                <Download className="w-4 h-4" />
                Download Template
              </Button>
            </div>
          </div>
        </div>
      </header>

      <main className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        <div className="bg-white shadow-sm rounded-lg p-8">
          <h1 className="text-3xl font-bold text-gray-900 mb-8">SAFE Agreement Template</h1>
          
          <div className="prose prose-lg max-w-none">
            <div className="bg-blue-50 border border-blue-200 rounded-lg p-6 mb-8">
              <h3 className="text-lg font-semibold text-blue-900 mb-2">Important Legal Notice</h3>
              <p className="text-blue-800">
                This template is for informational purposes only and does not constitute legal advice. 
                Please consult with a qualified attorney before using any legal documents for actual investments.
              </p>
            </div>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-gray-900 mb-4">What is a SAFE Agreement?</h2>
              <p className="text-gray-700 mb-4">
                A SAFE (Simple Agreement for Future Equity) is an investment contract that provides the investor 
                the right to purchase stock in a future equity round, subject to certain parameters.
              </p>
              <p className="text-gray-700 mb-4">
                SAFEs were created by Y Combinator as a simpler alternative to convertible notes, eliminating 
                interest rates and maturity dates while providing investor protections.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-gray-900 mb-4">Key Terms</h2>
              
              <div className="grid md:grid-cols-2 gap-6">
                <div className="bg-gray-50 p-6 rounded-lg">
                  <h3 className="text-lg font-medium text-gray-900 mb-3">Valuation Cap</h3>
                  <p className="text-gray-700">
                    The maximum company valuation at which the SAFE will convert to equity. 
                    This protects investors from excessive dilution.
                  </p>
                </div>

                <div className="bg-gray-50 p-6 rounded-lg">
                  <h3 className="text-lg font-medium text-gray-900 mb-3">Discount Rate</h3>
                  <p className="text-gray-700">
                    The percentage discount investors receive on the price per share 
                    in the next equity financing round.
                  </p>
                </div>

                <div className="bg-gray-50 p-6 rounded-lg">
                  <h3 className="text-lg font-medium text-gray-900 mb-3">Conversion Events</h3>
                  <p className="text-gray-700">
                    Specific events that trigger the SAFE to convert to equity, 
                    typically the next qualified financing round.
                  </p>
                </div>

                <div className="bg-gray-50 p-6 rounded-lg">
                  <h3 className="text-lg font-medium text-gray-900 mb-3">Pro Rata Rights</h3>
                  <p className="text-gray-700">
                    The right for investors to participate in future funding rounds 
                    to maintain their ownership percentage.
                  </p>
                </div>
              </div>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-gray-900 mb-4">How Fundry Uses SAFEs</h2>
              <p className="text-gray-700 mb-4">
                All investments made through Fundry are structured as SAFE agreements, providing:
              </p>
              <ul className="list-disc pl-6 text-gray-700 mb-4">
                <li>Simple, standardized investment terms</li>
                <li>Lower legal costs compared to traditional equity rounds</li>
                <li>Faster execution for both founders and investors</li>
                <li>Flexible conversion terms based on company performance</li>
              </ul>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-gray-900 mb-4">Investment Limits on Fundry</h2>
              <div className="bg-orange-50 border border-orange-200 rounded-lg p-6">
                <ul className="list-disc pl-6 text-orange-800">
                  <li>Maximum campaign funding: $5,000</li>
                  <li>Minimum individual investment: $25</li>
                  <li>Platform fee: 5% for amounts above $1,000 (free under $1,000)</li>
                </ul>
              </div>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-gray-900 mb-4">Legal Considerations</h2>
              <div className="bg-red-50 border border-red-200 rounded-lg p-6">
                <h3 className="text-lg font-semibold text-red-900 mb-2">Important Disclaimers</h3>
                <ul className="list-disc pl-6 text-red-800">
                  <li>This template is not a substitute for professional legal advice</li>
                  <li>Securities laws vary by jurisdiction and may affect your investment</li>
                  <li>Both parties should review all terms with qualified legal counsel</li>
                  <li>Investment in early-stage companies carries significant risk</li>
                </ul>
              </div>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-gray-900 mb-4">Resources</h2>
              <p className="text-gray-700 mb-4">
                For more information about SAFE agreements and startup investing:
              </p>
              <ul className="list-disc pl-6 text-gray-700 mb-4">
                <li>Y Combinator SAFE Agreement Documentation</li>
                <li>SEC Guidelines for Small Business Investment</li>
                <li>Fundry Investment Disclaimer and Risk Factors</li>
              </ul>
            </section>
          </div>
        </div>
      </main>
    </div>
  );
}